name: Build-Veloera

on: workflow_dispatch

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Veloera
    steps:
    
      - uses: actions/checkout@v4
    
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Clone Repo
        run: |
            echo "Fetching latest tag from Veloera repository..."
            export LATEST_APP=$(wget -qO- https://api.github.com/repos/Veloera/Veloera/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
            echo "Latest tag: $LATEST_APP"
            if [ -z "$LATEST_APP" ]; then
              echo "Failed to get latest tag, using main branch"
              git clone https://github.com/Veloera/Veloera
            else
              echo "Cloning with tag: $LATEST_APP"
              git clone -b $LATEST_APP https://github.com/Veloera/Veloera
            fi
            echo "Clone completed successfully"

      - name: Build Frontend
        env:
          CI: ""
        run: |
          echo "Starting frontend build process..."
          cd Veloera/web
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          echo "Installing dependencies..."
          bun install
          
          # 检查是否已有 vite.config.js 或 vite.config.ts
          if [ -f "vite.config.js" ] || [ -f "vite.config.ts" ]; then
            echo "Using existing vite config"
            cat vite.config.* || true
          else
            echo "Creating vite.config.js..."
            cat > vite.config.js << 'EOF'
          import { defineConfig } from "vite";
          import react from "@vitejs/plugin-react";
          
          export default defineConfig({
            plugins: [react()],
            build: {
              // 确保构建输出到正确的目录
              outDir: 'dist',
              // 确保资源使用相对路径
              base: './',
              rollupOptions: {
                output: {
                  // 确保文件名格式正确
                  entryFileNames: 'assets/[name].[hash].js',
                  chunkFileNames: 'assets/[name].[hash].js',
                  assetFileNames: 'assets/[name].[hash].[ext]'
                }
              }
            },
            esbuild: {
              loader: "jsx",
              include: /src\/.*\.[jt]sx?$/,
              exclude: []
            },
            optimizeDeps: {
              esbuildOptions: {
                loader: {
                  ".js": "jsx"
                }
              }
            }
          });
          EOF
          fi
          
          echo "Getting version info..."
          export VERSION_INFO=$(git describe --tags 2>/dev/null || echo "unknown")
          echo "Version: $VERSION_INFO"
          
          echo "Starting build..."
          DISABLE_ESLINT_PLUGIN='true' VITE_REACT_APP_VERSION="$VERSION_INFO" bun run build
          
          echo "Build completed, verifying frontend output..."
          if [ -d "dist" ]; then
            echo "✅ dist directory created successfully"
            echo "Files in dist:"
            ls -la dist/
            echo "Total files: $(find dist -type f | wc -l)"
            echo "Dist size: $(du -sh dist)"
            
            # 验证关键文件
            if [ -f "dist/index.html" ]; then
              echo "✅ index.html found"
              echo "index.html size: $(ls -lh dist/index.html | awk '{print $5}')"
              # 检查 index.html 内容
              echo "First 500 chars of index.html:"
              head -c 500 dist/index.html
              echo ""
              
              # 确保index.html不为空
              if [ -s "dist/index.html" ]; then
                echo "✅ index.html is not empty"
              else
                echo "ERROR: index.html is empty!"
                exit 1
              fi
            else
              echo "ERROR: index.html not found in dist!"
              exit 1
            fi
            
            # 检查是否有 assets 目录
            if [ -d "dist/assets" ]; then
              echo "✅ assets directory found"
              echo "Files in assets:"
              ls -la dist/assets/ | head -20
            fi
          else
            echo "ERROR: dist directory not found!"
            exit 1
          fi
          
          cd ../..
          echo "Frontend build process completed"

      - name: Check Go Embed Implementation
        run: |
          echo "Checking for embed implementation in Veloera..."
          cd Veloera
          
          # 查找包含 go:embed 的文件
          echo "Files containing go:embed directive:"
          grep -r "//go:embed" . --include="*.go" || echo "No embed directives found"
          
          # 查找 main.go 或类似文件
          echo -e "\nLooking for main.go or similar files:"
          find . -name "main.go" -o -name "server.go" -o -name "web.go" | head -10
          
          # 检查是否有正确的 embed 实现
          echo -e "\nChecking embed patterns:"
          grep -r "embed\.FS" . --include="*.go" | head -10 || echo "No embed.FS usage found"
          
          cd ..

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Patch Embed Implementation if Needed
        run: |
          echo "Checking and patching embed implementation..."
          cd Veloera
          
          # 查找主文件
          MAIN_FILE=$(find . -name "main.go" | head -1)
          if [ -z "$MAIN_FILE" ]; then
            echo "main.go not found, looking for alternatives..."
            MAIN_FILE=$(find . -name "*.go" -exec grep -l "func main()" {} \; | head -1)
          fi
          
          echo "Main file: $MAIN_FILE"
          
          # 检查是否需要修补 embed 实现
          if [ -n "$MAIN_FILE" ]; then
            # 检查是否已有正确的 embed 指令
            if ! grep -q "//go:embed all:web/dist" "$MAIN_FILE" && ! grep -q "//go:embed web/dist" "$MAIN_FILE"; then
              echo "Patching embed implementation..."
              
              # 创建补丁文件
              cat > embed_patch.go << 'EOF'
// This file ensures proper embedding of web assets
package main

import (
	"embed"
	"io/fs"
)

//go:embed all:web/dist
var webFS embed.FS

// GetWebFS returns the embedded web filesystem
func GetWebFS() (fs.FS, error) {
	return fs.Sub(webFS, "web/dist")
}
EOF
              
              # 如果文件在子目录，调整 package
              PKG_NAME=$(head -1 "$MAIN_FILE" | awk '{print $2}')
              sed -i "s/package main/package $PKG_NAME/" embed_patch.go
              
              # 将补丁文件放到主文件同目录
              cp embed_patch.go $(dirname "$MAIN_FILE")/
              
              echo "✅ Embed patch applied"
            else
              echo "✅ Embed directive already exists"
            fi
          fi
          
          cd ..
          
      - name: Build Backend
        run: |
          echo "Starting backend build process..."
          cd Veloera
          
          # 设置Go交叉编译环境变量
          export GOOS=freebsd
          export GOARCH=amd64
          export CGO_ENABLED=0
          
          echo "Go environment:"
          go version
          echo "GOOS: $GOOS"
          echo "GOARCH: $GOARCH"
          echo "CGO_ENABLED: $CGO_ENABLED"
          
          # 下载依赖，添加重试机制
          echo "Downloading Go modules..."
          for i in 1 2 3; do
            if go mod download; then
              echo "✅ Go modules downloaded successfully"
              break
            else
              echo "Attempt $i failed, retrying..."
              sleep 5
            fi
          done
          
          # 验证模块
          go mod verify
          
          # 动态获取正确的模块名
          MODULE_NAME=$(head -1 go.mod | awk '{print $2}')
          echo "Using module name: $MODULE_NAME"
          
          # 获取版本信息
          VERSION_INFO=$(git describe --tags 2>/dev/null || echo "v0.0.0-unknown")
          echo "Building with version: $VERSION_INFO"
          
          # 再次验证前端文件
          if [ ! -f "web/dist/index.html" ]; then
            echo "ERROR: Frontend dist/index.html not found!"
            echo "Available files in web/:"
            ls -la web/ || echo "web directory not found"
            exit 1
          fi
          
          echo "✅ Frontend verification passed"
          echo "Frontend dist directory contents:"
          ls -la web/dist/
          echo "Assets directory contents (if exists):"
          ls -la web/dist/assets/ 2>/dev/null || echo "No assets directory"
          
          # 构建FreeBSD二进制文件
          echo "Building FreeBSD binary..."
          go build -ldflags "-s -w -X '${MODULE_NAME}/common.Version=${VERSION_INFO}'" -o veloera-freebsd
          
          # 验证二进制文件
          if [ ! -f "veloera-freebsd" ]; then
            echo "ERROR: Binary file not created!"
            exit 1
          fi
          
          # 验证二进制文件大小
          BINARY_SIZE=$(stat -c%s veloera-freebsd)
          BINARY_SIZE_MB=$((BINARY_SIZE / 1024 / 1024))
          echo "Binary size: $BINARY_SIZE bytes (${BINARY_SIZE_MB} MB)"
          
          # 检查是否包含前端资源（应该>10MB）
          if [ $BINARY_SIZE -lt 10000000 ]; then
            echo "WARNING: Binary size seems small (${BINARY_SIZE_MB}MB), frontend might not be embedded correctly"
            echo "Checking for embedded resources..."
            
            # 检查多个关键字符串
            FOUND_EMBED=false
            for keyword in "index.html" "<!DOCTYPE html>" "assets" ".js" ".css"; do
              if strings veloera-freebsd | grep -q "$keyword"; then
                echo "✅ Found '$keyword' in binary"
                FOUND_EMBED=true
              fi
            done
            
            if [ "$FOUND_EMBED" = false ]; then
              echo "ERROR: No frontend resources found in binary!"
              echo "This usually means the embed directive is not working correctly."
              exit 1
            fi
          else
            echo "✅ Binary size looks good (${BINARY_SIZE_MB}MB) - frontend likely embedded correctly"
            
            # 额外验证
            echo "Verifying embedded content..."
            if strings veloera-freebsd | grep -q "<!DOCTYPE html>"; then
              echo "✅ HTML content found in binary"
            fi
            if strings veloera-freebsd | grep -q ".js"; then
              echo "✅ JavaScript files found in binary"
            fi
          fi
          
          # 验证版本信息注入
          if strings veloera-freebsd | grep -q "$VERSION_INFO"; then
            echo "✅ Version information successfully injected: $VERSION_INFO"
          else
            echo "WARNING: Version information might not be injected correctly"
          fi
          
          # 验证目标平台
          file veloera-freebsd
          echo "✅ Backend build completed successfully"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: veloera-freebsd
          path: Veloera/veloera-freebsd
  
      - name: Generate release tag
        id: tag
        run: |
          # 获取远程仓库的最新标签
          REMOTE_TAG=$(wget -qO- https://api.github.com/repos/Veloera/Veloera/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          echo "Remote tag: $REMOTE_TAG"
          
          # 生成本地构建标签
          if [ -n "$REMOTE_TAG" ]; then
            BUILD_TAG="${REMOTE_TAG}-freebsd-$(date +%Y%m%d-%H%M%S)"
          else
            BUILD_TAG="v1.0.0-freebsd-$(date +%Y%m%d-%H%M%S)"
          fi
          
          echo "Generated build tag: $BUILD_TAG"
          echo "release_tag=$BUILD_TAG" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: "Veloera FreeBSD Build - ${{ steps.tag.outputs.release_tag }}"
          body: |
            ## Veloera FreeBSD 构建版本
            
            基于 Veloera 项目的 FreeBSD 二进制文件构建
            
            ### 构建信息
            - 构建时间: ${{ github.run_id }}
            - 目标平台: FreeBSD amd64
            - 构建环境: Ubuntu + Go 交叉编译
            
            ### 使用说明
            1. 下载 `veloera-freebsd` 二进制文件
            2. 上传到 FreeBSD 服务器
            3. 添加执行权限: `chmod +x veloera-freebsd`
            4. 运行: `./veloera-freebsd`
            
            ### 修复内容
            - ✅ 修复前端资源嵌入问题
            - ✅ 使用 all: 前缀确保所有文件被嵌入
            - ✅ 改进的构建验证流程
            - ✅ 增强的错误检测和报告
          files: Veloera/veloera-freebsd
          draft: false
          prerelease: false
              
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8
